export const ActionTypes = {
  GET_TODO_LIST_BEGIN: "GET_TODO_LIST_BEGIN",
  GET_TODO_LIST: "GET_TODO_LIST",
  GET_TODO_LIST_SUCCESS: "GET_TODO_LIST_SUCCESS",
  GET_TODO_LIST_FAILURE: "GET_TODO_LIST_FAILURE",

  DELETE_TODO_BEGIN: "DELETE_TODO_BEGIN",
  DELETE_TODO: "DELETE_TODO",
  DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",

  GET_TODO_DETAIL_BEGIN: "GET_TODO_DETAIL_BEGIN",
  GET_TODO_DETAIL: "GET_TODO_DETAIL",
  GET_TODO_DETAIL_SUCCESS: "GET_TODO_DETAIL_SUCCESS",
  GET_TODO_DETAIL_FAILURE: "GET_TODO_DETAIL_FAILURE",

  ADD_UPDATE_TODO_BEGIN: "ADD_UPDATE_TODO_BEGIN",
  ADD_UPDATE_TODO: "ADD_UPDATE_TODO",
  ADD_UPDATE_TODO_SUCCESS: "ADD_UPDATE_TODO_SUCCESS",
  ADD_UPDATE_TODO_FAILURE: "ADD_UPDATE_TODO_FAILURE",
};
